### ISSUE TITLE
Add Photo Capturing for Cordova App

### ISSUE THREAD

**Issue by OZhurbenko** [PRJ-ESIT/ESIT-web#36]
It should be in the pre-authorized debit form.

**Comment by OZhurbenko** [comment]
Base component was added in #65 , but this is what still needs to be done in order to complete the task:
- Figure how to save the picture locally in the app, since by default it appears in the /tmp folder
- Integrate it into the Sales as the last step of the Sale creation once DocuSign part is completed
- Submit the picture to the Box

**Comment by K-LV** [comment]
Fixed with https://github.com/PRJ-ESIT/ESIT-web/pull/114
