### ISSUE TITLE
Add Address information for Employees to database

### ISSUE THREAD

**Issue by K-LV** [PRJ-ESIT/ESIT-web#60]
Our DB is missing Address information for Employees. Similar to what we have for Customers. We need: address, unit, city, postal code, and province.

Edit: It could be as simple as adding an Address FK to the Employee table.

**Comment by mmarangoni** [comment]
Please include "notes" to the installation form on db as well, it seems to be missing.

**Comment by OZhurbenko** [comment]
Will do, good catch!
